In [ ]:
import pandas as pd
data=pd.read_csv('C:\\Users\\wangy\\Desktop\\2015_Street_Tree_Census_-_Tree_Data.csv')
data.head()

,tree_id,block_id,created_at,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,spc_common,...,boro_ct,state,latitude,longitude,x_sp,y_sp,council district,census tract,bin,bbl
0,180683,348711,08/27/2015,3,0,OnCurb,Alive,Fair,Acer rubrum,red maple,...,4073900,New York,40.723092,-73.844215,1027431.148,202756.7687,29.0,739.0,4052307.0,4.022210e+09
1,200540,315986,09/03/2015,21,0,OnCurb,Alive,Fair,Quercus palustris,pin oak,...,4097300,New York,40.794111,-73.818679,1034455.701,228644.8374,19.0,973.0,4101931.0,4.044750e+09
2,204026,218365,09/05/2015,3,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,honeylocust,...,3044900,New York,40.717581,-73.936608,1001822.831,200716.8913,34.0,449.0,3338310.0,3.028870e+09
3,204337,217969,09/05/2015,10,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,honeylocust,...,3044900,New York,40.713537,-73.934456,1002420.358,199244.2531,34.0,449.0,3338342.0,3.029250e+09
4,189565,223043,08/30/2015,21,0,OnCurb,Alive,Good,Tilia americana,American linden,...,3016500,New York,40.666778,-73.975979,990913.775,182202.4260,39.0,165.0,3025654.0,3.010850e+09

In [ ]:
sanityindex=(data.status=='Alive')&(data.steward=='None')&(data.guards=='None')&(data.health=='Good')
data=data[sanityindex]
len(data)

385729

In [ ]:
selectedNames1= ['latitude', 'longitude','spc_latin']
data2= data[selectedNames1].reset_index(drop=True)
data2.dropna(inplace=True)
data2.reset_index(drop=True, inplace=True)
data2['genus'] = data2['spc_latin'].str.split(' ').apply(lambda x: x[0])
selectedNames2= ['latitude', 'longitude','genus']
data2= data2[selectedNames2].reset_index(drop=True)
data2.head()

    latitude  longitude      genus
0  40.713537 -73.934456  Gleditsia
1  40.666778 -73.975979      Tilia
2  40.762724 -73.987297      Tilia
3  40.596579 -74.076255  Gleditsia
4  40.782428 -73.911171   Platanus

In [ ]:
data3=data2.groupby('genus').count().sort_values(by='latitude').tail(15)
data3

               latitude  longitude
genus
Koelreuteria       2060       2060
Syringa            2515       2515
Liquidambar        6853       6853
Ulmus              8263       8263
Styphnolobium      9994       9994
Ginkgo            10472      10472
Fraxinus          13025      13025
Zelkova           17378      17378
Prunus            22309      22309
Tilia             29240      29240
Pyrus             32373      32373
Gleditsia         38345      38345
Acer              51771      51771
Quercus           52310      52310
Platanus          61528      61528

In [ ]:
data3.index

Index(['Koelreuteria', 'Syringa', 'Liquidambar', 'Ulmus', 'Styphnolobium',
       'Ginkgo', 'Fraxinus', 'Zelkova', 'Prunus', 'Tilia', 'Pyrus',
       'Gleditsia', 'Acer', 'Quercus', 'Platanus'],
      dtype='object', name='genus')

In [ ]:
list1 = '|'.join(list(data3.index))
data2 = data2[data2['genus'].str.contains(list1)].reset_index(drop=True)
list1 = '|'.join(list(data3.index))
data2

         latitude  longitude      genus
0       40.713537 -73.934456  Gleditsia
1       40.666778 -73.975979      Tilia
2       40.762724 -73.987297      Tilia
3       40.596579 -74.076255  Gleditsia
4       40.782428 -73.911171   Platanus
...           ...        ...        ...
358431  40.609541 -73.945835   Platanus
358432  40.645694 -73.958179    Quercus
358433  40.713211 -73.954944    Quercus
358434  40.620762 -74.136517       Acer
358435  40.850828 -73.903115       Acer

[358436 rows x 3 columns]

In [ ]:
df=data2.groupby('genus')
df.groups

{'Acer': [7, 8, 26, 27, 32, 40, 57, 59, 61, 135, 136, 137, 138, 139, 141, 142, 143, 144, 146, 147, 153, 154, 155, 156, 158, 162, 163, 164, 165, 230, 231, 232, 236, 237, 238, 241, 242, 244, 245, 246, 247, 256, 257, 258, 264, 265, 266, 292, 308, 309, 310, 311, 350, 351, 352, 359, 360, 361, 362, 367, 368, 371, 372, 373, 374, 375, 381, 384, 385, 388, 389, 390, 391, 396, 397, 398, 399, 400, 401, 402, 405, 406, 407, 408, 410, 411, 412, 414, 415, 416, 425, 426, 427, 428, 429, 430, 431, 436, 437, 440, ...], 'Fraxinus': [53, 629, 650, 651, 652, 653, 654, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 928, 929, 930, 931, 932, 933, 934, 935, 994, 995, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1215, 1216, 1217, 1276, 1277, 1278, 1279, 1284, 1285, 1286, 1287, 1288, 1289, 1772, 1773, 1774, 1775, 1776, 1777, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1979, 1980, 1981, 1982, 2106, 2107, 2108, 2109, 2110, 2111, 2112, 2113, 2114, 2115, 2147, 2148, 2149, 2195, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2203, 2817, 2907, 2908, 2909, 2910, 2911, 2912, 2913, 2914, 2915, 2945, 2946, 2947, ...], 'Ginkgo': [66, 68, 77, 78, 79, 82, 90, 95, 102, 103, 104, 105, 108, 114, 115, 120, 122, 124, 152, 198, 221, 222, 248, 249, 272, 328, 329, 433, 561, 586, 730, 779, 800, 1119, 1227, 1249, 1250, 1251, 1298, 1300, 1301, 1307, 1332, 1334, 1358, 1389, 1568, 1572, 1633, 1702, 1745, 1911, 1913, 1916, 1922, 1925, 2022, 2049, 2105, 2118, 2123, 2124, 2145, 2154, 2192, 2228, 2251, 2263, 2265, 2277, 2282, 2298, 2299, 2307, 2320, 2328, 2366, 2367, 2382, 2741, 2749, 2766, 2827, 2845, 2846, 2847, 2854, 2858, 2899, 2901, 2902, 2927, 2938, 2973, 2984, 2985, 3000, 3001, 3005, 3014, ...], 'Gleditsia': [0, 3, 5, 6, 10, 11, 12, 13, 14, 64, 65, 67, 69, 74, 75, 76, 80, 81, 85, 86, 87, 88, 92, 93, 94, 96, 97, 99, 101, 106, 109, 110, 111, 112, 113, 116, 117, 119, 121, 123, 148, 149, 150, 159, 174, 177, 182, 187, 188, 199, 200, 201, 206, 207, 208, 209, 210, 219, 220, 233, 234, 235, 250, 270, 271, 275, 276, 324, 325, 327, 330, 331, 332, 333, 334, 363, 365, 380, 392, 393, 394, 395, 417, 418, 432, 434, 435, 487, 488, 501, 560, 562, 563, 564, 587, 588, 596, 597, 598, 600, ...], 'Koelreuteria': [780, 782, 841, 843, 844, 849, 850, 914, 1058, 1059, 1078, 1079, 1080, 1081, 1082, 1083, 1085, 1293, 1353, 1354, 1355, 1375, 1376, 1440, 1500, 1843, 1938, 1999, 2000, 2004, 7939, 7951, 7966, 7968, 7969, 7986, 7987, 7991, 8001, 8074, 8075, 8076, 8077, 8084, 8085, 8087, 8088, 8089, 8090, 8092, 8093, 8094, 8119, 8120, 8121, 8122, 8123, 8124, 8141, 8142, 8159, 8160, 8161, 8162, 8167, 8168, 8223, 8224, 8225, 8226, 8227, 8330, 8881, 8882, 8883, 8956, 8957, 10858, 10859, 10860, 11060, 11099, 11170, 11171, 11172, 11539, 11621, 11676, 11677, 11678, 11714, 11715, 15266, 15267, 15268, 15356, 15380, 15418, 15419, 15420, ...], 'Liquidambar': [195, 214, 215, 229, 259, 260, 261, 299, 302, 342, 347, 420, 422, 455, 603, 823, 825, 826, 893, 894, 900, 947, 948, 949, 1028, 1096, 1101, 1267, 1268, 1377, 1380, 1382, 1599, 1601, 1653, 1693, 1797, 1823, 1825, 1830, 1838, 1897, 2737, 2739, 3084, 3087, 3092, 3095, 3163, 3165, 3192, 3209, 3213, 3214, 3231, 3232, 3234, 3237, 3240, 3241, 3253, 3260, 3280, 3299, 3349, 3369, 3370, 3485, 3522, 3683, 3684, 3887, 3888, 4073, 4074, 4075, 4220, 4484, 4487, 5753, 5757, 5792, 5793, 5798, 5801, 5804, 5851, 5852, 5853, 5888, 5913, 5914, 5916, 5999, 6000, 6033, 6034, 6043, 6045, 6051, ...], 'Platanus': [4, 9, 15, 17, 18, 19, 20, 23, 24, 31, 33, 34, 36, 37, 38, 39, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 54, 55, 56, 98, 127, 128, 129, 130, 131, 132, 133, 134, 160, 161, 166, 167, 169, 170, 239, 240, 243, 251, 252, 254, 255, 441, 442, 443, 445, 446, 447, 448, 449, 462, 463, 478, 479, 481, 482, 483, 484, 485, 486, 502, 503, 506, 507, 508, 509, 510, 511, 512, 515, 516, 517, 518, 519, 520, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 555, 556, 557, 558, ...], 'Prunus': [140, 145, 885, 915, 937, 938, 968, 969, 970, 971, 972, 998, 1004, 1005, 1006, 1043, 1045, 1046, 1047, 1095, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1142, 1143, 1232, 1595, 1596, 1597, 1598, 1610, 1623, 1624, 1625, 1626, 1627, 1628, 1644, 1699, 1710, 1711, 1712, 1751, 1752, 1753, 1754, 1755, 1759, 1760, 1761, 1762, 1764, 1794, 1821, 1822, 1845, 1846, 1847, 1898, 1899, 1900, 1901, 1905, 1906, 1907, 1908, 1953, 1959, 1960, 2009, 2010, 2019, 2388, 2756, 2757, 2758, 2759, 2760, 2768, 2781, 2795, 2796, 2797, 2798, 2799, 2800, 2801, 2802, 2803, 2860, 2861, 2862, 2867, 2868, 2869, ...], 'Pyrus': [178, 179, 180, 181, 267, 268, 269, 277, 278, 279, 280, 281, 282, 353, 354, 355, 356, 357, 358, 369, 370, 403, 612, 667, 668, 669, 670, 671, 680, 681, 682, 683, 685, 764, 811, 812, 814, 815, 834, 835, 836, 837, 862, 881, 882, 883, 884, 905, 906, 925, 926, 927, 983, 989, 990, 991, 992, 993, 1070, 1072, 1105, 1106, 1107, 1108, 1109, 1111, 1112, 1114, 1121, 1123, 1124, 1125, 1126, 1127, 1144, 1145, 1146, 1147, 1148, 1210, 1211, 1212, 1213, 1299, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1403, 1405, 1407, 1408, 1409, 1411, ...], 'Quercus': [16, 21, 22, 25, 28, 29, 30, 58, 60, 62, 63, 70, 71, 72, 73, 83, 84, 157, 168, 171, 172, 173, 183, 184, 185, 186, 189, 212, 213, 217, 218, 224, 225, 226, 253, 274, 287, 288, 291, 293, 294, 295, 296, 297, 298, 312, 313, 314, 315, 316, 344, 345, 348, 364, 382, 383, 386, 387, 413, 423, 438, 439, 454, 472, 500, 522, 534, 535, 536, 537, 538, 539, 594, 610, 611, 620, 630, 631, 634, 635, 636, 637, 638, 639, 642, 662, 663, 665, 696, 697, 698, 699, 700, 702, 703, 704, 705, 720, 721, 722, ...], 'Styphnolobium': [175, 176, 191, 192, 193, 194, 196, 197, 202, 203, 204, 211, 216, 227, 228, 262, 263, 286, 289, 290, 300, 301, 303, 304, 305, 306, 307, 335, 336, 337, 338, 339, 340, 341, 343, 346, 349, 376, 377, 409, 419, 421, 602, 604, 605, 606, 607, 608, 609, 660, 661, 824, 846, 847, 892, 895, 896, 897, 899, 901, 902, 903, 904, 961, 962, 963, 964, 965, 966, 1029, 1031, 1032, 1033, 1034, 1068, 1069, 1098, 1099, 1100, 1103, 1104, 1203, 1204, 1264, 1265, 1266, 1321, 1378, 1379, 1381, 1383, 1384, 1429, 1600, 1602, 1603, 1638, 1654, 1692, 1694, ...], 'Syringa': [644, 645, 719, 763, 821, 822, 1660, 1713, 1714, 1715, 1758, 5684, 5743, 6269, 6270, 6292, 6293, 6294, 6295, 6296, 6307, 6308, 6309, 6310, 6311, 6315, 6316, 6317, 6318, 6321, 6322, 6357, 8794, 8795, 8796, 8848, 8849, 8850, 8851, 8852, 9660, 9661, 9662, 9779, 9780, 10955, 10956, 11019, 11020, 11021, 11381, 11382, 11383, 11438, 11439, 11440, 12140, 12141, 12159, 12160, 12161, 12162, 12287, 12323, 12324, 13854, 13867, 13868, 13871, 13872, 13873, 14075, 14076, 14100, 14101, 14102, 14103, 14176, 14521, 14540, 14541, 14542, 15362, 17888, 18713, 18714, 19180, 19181, 19182, 22281, 22282, 22309, 22340, 22507, 22508, 22625, 22703, 23011, 23012, 23013, ...], 'Tilia': [1, 2, 89, 91, 100, 107, 118, 125, 126, 151, 190, 205, 223, 283, 284, 285, 326, 366, 378, 379, 404, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 550, 551, 552, 553, 554, 559, 672, 673, 674, 675, 676, 677, 678, 679, 684, 686, 709, 713, 727, 813, 857, 861, 864, 867, 907, 908, 975, 976, 977, 978, 979, 980, 1023, 1024, 1025, 1026, 1027, 1044, 1073, 1074, 1075, 1076, 1077, 1110, 1115, 1116, 1117, 1118, 1122, 1166, 1167, 1168, 1169, 1170, 1171, 1193, 1226, 1263, 1302, 1303, 1314, 1338, 1339, 1340, 1341, 1356, 1357, 1371, 1388, ...], 'Ulmus': [35, 464, 614, 615, 691, 795, 839, 856, 872, 877, 1052, 1053, 1054, 1055, 1056, 1130, 1177, 1433, 1449, 1450, 1487, 1515, 1521, 1592, 1605, 1640, 1641, 1642, 1643, 1675, 1676, 1677, 1678, 1679, 1716, 1717, 1727, 1809, 1833, 1834, 1848, 1849, 1850, 1851, 1852, 1864, 1954, 2082, 2099, 2159, 2238, 2254, 2255, 2267, 2268, 2269, 2270, 2271, 2403, 2470, 2498, 2499, 2517, 2525, 2529, 2548, 2657, 2674, 2761, 2806, 3355, 3374, 3449, 3560, 3562, 3579, 3596, 3614, 3657, 3703, 3713, 3715, 3745, 3767, 3768, 3771, 3784, 3809, 3828, 3829, 3832, 3841, 3866, 3879, 3880, 3892, 3938, 3943, 3952, 3953, ...], 'Zelkova': [273, 317, 318, 319, 320, 321, 322, 323, 424, 459, 460, 461, 473, 499, 521, 523, 524, 525, 565, 632, 633, 655, 656, 657, 658, 659, 784, 785, 786, 838, 851, 939, 941, 942, 943, 944, 1000, 1001, 1002, 1003, 1090, 1128, 1129, 1131, 1190, 1191, 1192, 1214, 1243, 1244, 1246, 1413, 1451, 1452, 1462, 1482, 1483, 1486, 1507, 1508, 1509, 1510, 1511, 1524, 1525, 1526, 1527, 1528, 1537, 1538, 1649, 2288, 2291, 2292, 2294, 2296, 2297, 2312, 2314, 2315, 2316, 2317, 2318, 2321, 2322, 2323, 2331, 2332, 2333, 2343, 2344, 2348, 2349, 2358, 2359, 2369, 2370, 2372, 2373, 2374, ...]}

In [ ]:
def typicalSampling(group):
    
    return group.sample(n=300)

In [ ]:
result=data2.groupby('genus',group_keys=False).apply(typicalSampling).reset_index(drop=True)
len(result)

4500

In [ ]:
result

       latitude  longitude    genus
0     40.871645 -73.852622     Acer
1     40.561168 -74.181661     Acer
2     40.684241 -73.788480     Acer
3     40.863976 -73.830723     Acer
4     40.588873 -74.153231     Acer
...         ...        ...      ...
4495  40.709965 -73.897958  Zelkova
4496  40.510212 -74.234147  Zelkova
4497  40.697813 -73.841222  Zelkova
4498  40.614405 -73.985595  Zelkova
4499  40.877681 -73.885259  Zelkova

[4500 rows x 3 columns]

In [ ]:
result.groupby('genus').count()

               latitude  longitude
genus
Acer                300        300
Fraxinus            300        300
Ginkgo              300        300
Gleditsia           300        300
Koelreuteria        300        300
Liquidambar         300        300
Platanus            300        300
Prunus              300        300
Pyrus               300        300
Quercus             300        300
Styphnolobium       300        300
Syringa             300        300
Tilia               300        300
Ulmus               300        300
Zelkova             300        300

In [ ]:
df_new=pd.get_dummies(result)

df_new

,latitude,longitude,genus_Acer,genus_Fraxinus,genus_Ginkgo,genus_Gleditsia,genus_Koelreuteria,genus_Liquidambar,genus_Platanus,genus_Prunus,genus_Pyrus,genus_Quercus,genus_Styphnolobium,genus_Syringa,genus_Tilia,genus_Ulmus,genus_Zelkova
0,40.871645,-73.852622,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,40.561168,-74.181661,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,40.684241,-73.788480,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,40.863976,-73.830723,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,40.588873,-74.153231,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,40.709965,-73.897958,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4496,40.510212,-74.234147,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4497,40.697813,-73.841222,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4498,40.614405,-73.985595,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4499,40.877681,-73.885259,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [ ]:
!pip install pgmpy

Requirement already satisfied: pgmpy in c:\anaconda3\envs\geo\lib\site-packages (0.1.18)
Requirement already satisfied: networkx in c:\anaconda3\envs\geo\lib\site-packages (from pgmpy) (2.5)
Requirement already satisfied: numpy in c:\anaconda3\envs\geo\lib\site-packages (from pgmpy) (1.21.3)
Requirement already satisfied: scikit-learn in c:\anaconda3\envs\geo\lib\site-packages (from pgmpy) (1.0)
Requirement already satisfied: pyparsing in c:\anaconda3\envs\geo\lib\site-packages (from pgmpy) (2.4.7)
Requirement already satisfied: pandas in c:\anaconda3\envs\geo\lib\site-packages (from pgmpy) (1.3.4)
Requirement already satisfied: joblib in c:\anaconda3\envs\geo\lib\site-packages (from pgmpy) (1.1.0)
Requirement already satisfied: torch in c:\anaconda3\envs\geo\lib\site-packages (from pgmpy) (1.11.0)
Requirement already satisfied: statsmodels in c:\anaconda3\envs\geo\lib\site-packages (from pgmpy) (0.13.0)
Requirement already satisfied: scipy in c:\anaconda3\envs\geo\lib\site-packages (from pgmpy) (1.7.1)
Requirement already satisfied: tqdm in c:\anaconda3\envs\geo\lib\site-packages (from pgmpy) (4.62.3)
Requirement already satisfied: decorator>=4.3.0 in c:\anaconda3\envs\geo\lib\site-packages (from networkx->pgmpy) (5.1.0)
Requirement already satisfied: pytz>=2017.3 in c:\anaconda3\envs\geo\lib\site-packages (from pandas->pgmpy) (2021.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\anaconda3\envs\geo\lib\site-packages (from pandas->pgmpy) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\anaconda3\envs\geo\lib\site-packages (from python-dateutil>=2.7.3->pandas->pgmpy) (1.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\anaconda3\envs\geo\lib\site-packages (from scikit-learn->pgmpy) (3.0.0)
Requirement already satisfied: patsy>=0.5.2 in c:\anaconda3\envs\geo\lib\site-packages (from statsmodels->pgmpy) (0.5.2)
Requirement already satisfied: typing-extensions in c:\anaconda3\envs\geo\lib\site-packages (from torch->pgmpy) (3.10.0.2)
Requirement already satisfied: colorama in c:\anaconda3\envs\geo\lib\site-packages (from tqdm->pgmpy) (0.4.4)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, WhiteKernel
from matplotlib import pyplot as plt
from pgmpy.estimators import HillClimbSearch, BicScore
import matplotlib.pylab as plt

In [ ]:
df_new.columns

Index(['latitude', 'longitude', 'genus_Acer', 'genus_Fraxinus', 'genus_Ginkgo',
       'genus_Gleditsia', 'genus_Koelreuteria', 'genus_Liquidambar',
       'genus_Platanus', 'genus_Prunus', 'genus_Pyrus', 'genus_Quercus',
       'genus_Styphnolobium', 'genus_Syringa', 'genus_Tilia', 'genus_Ulmus',
       'genus_Zelkova'],
      dtype='object')

In [ ]:
X_obs = df_new[['latitude', 'longitude']]
y_obs = df_new[['genus_Acer', 'genus_Fraxinus', 'genus_Ginkgo',
       'genus_Gleditsia', 'genus_Koelreuteria', 'genus_Liquidambar',
       'genus_Platanus', 'genus_Prunus', 'genus_Pyrus', 'genus_Quercus',
       'genus_Styphnolobium', 'genus_Syringa', 'genus_Tilia', 'genus_Ulmus',
       'genus_Zelkova']]

In [ ]:
kernel = 1.* RBF(length_scale=1., length_scale_bounds=(1e-3, 1e3)) \
    + WhiteKernel(noise_level=1., noise_level_bounds=(1e-10, 1e10))

gp = GaussianProcessRegressor(kernel=kernel,random_state=1)

gp.fit(X_obs, y_obs)

y_mesh_pred, sigma = gp.predict(X_obs, return_std=True)

print(gp.kernel_)

0.07**2 * RBF(length_scale=0.067) + WhiteKernel(noise_level=0.0608)

In [ ]:
y_mesh_pred

array([[ 0.09370309,  0.08457668,  0.06828159, ...,  0.08532733,
         0.08108688,  0.04958008],
       [ 0.15548938,  0.11913946, -0.0007249 , ...,  0.01900572,
         0.04066212,  0.01746979],
       [ 0.05124508,  0.07718115,  0.07992448, ...,  0.08525496,
         0.03929871,  0.06924171],
       ...,
       [ 0.05708955,  0.11528611,  0.07634961, ...,  0.06624478,
         0.02491674,  0.05627911],
       [ 0.04495902,  0.07868961,  0.06232896, ...,  0.07286755,
         0.0785234 ,  0.09936788],
       [ 0.06201473,  0.07575829,  0.05762009, ...,  0.08733215,
         0.11265775,  0.06411354]])

In [ ]:
kernel=0.07**2 * RBF(length_scale=0.067) + WhiteKernel(noise_level=0.0608)


gp = GaussianProcessRegressor(kernel=kernel,random_state=1)
gp.fit(X_obs, y_obs)
y_pred, sigma = gp.predict(X_obs, return_std=True)
print(gp.log_marginal_likelihood_value_)

-1675.1047614431855

In [ ]:
y_pred

array([[ 0.09370272,  0.08457406,  0.06828101, ...,  0.08532685,
         0.08108925,  0.04958048],
       [ 0.1554854 ,  0.11913462, -0.00072434, ...,  0.01900707,
         0.04066184,  0.0174716 ],
       [ 0.05124598,  0.07718155,  0.07992338, ...,  0.0852547 ,
         0.0392986 ,  0.06924046],
       ...,
       [ 0.05708749,  0.11528427,  0.07634499, ...,  0.06624634,
         0.02491671,  0.05627989],
       [ 0.04495874,  0.0786885 ,  0.0623319 , ...,  0.0728651 ,
         0.07852424,  0.09936508],
       [ 0.06201334,  0.0757563 ,  0.05762187, ...,  0.08733031,
         0.11265834,  0.06411349]])

In [ ]:
df1 = pd.DataFrame(y_pred)

df1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0.093703,0.084574,0.068281,0.058319,0.039194,0.040789,0.041499,0.062922,0.071285,0.075300,0.081834,0.062797,0.085327,0.081089,0.049580
1,0.155485,0.119135,-0.000724,0.045550,0.059175,0.223421,0.019762,0.039941,0.161894,0.042359,0.016860,0.053506,0.019007,0.040662,0.017472
2,0.051246,0.077182,0.079923,0.041109,0.083857,0.033001,0.066534,0.094443,0.031681,0.059697,0.087946,0.100923,0.085255,0.039299,0.069240
3,0.120817,0.071793,0.064686,0.038733,0.036157,0.044469,0.045697,0.070579,0.092363,0.047515,0.068305,0.068903,0.076764,0.075945,0.040081
4,0.137708,0.061962,0.001551,0.043168,0.105068,0.230636,0.053192,0.053875,0.102783,0.046827,0.031712,0.062022,0.026671,0.041662,0.029435
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,0.048766,0.114880,0.018295,0.105246,0.064188,0.033396,0.085104,0.068094,0.045833,0.077913,0.071677,0.045953,0.084643,0.049009,0.078136
4496,0.064362,0.071293,0.024489,0.012413,-0.003322,0.225118,0.015266,0.074844,0.243836,0.025929,0.009187,0.049409,0.041082,0.014237,0.025991
4497,0.057087,0.115284,0.076345,0.070999,0.058297,0.010932,0.089748,0.071200,0.041404,0.095307,0.061041,0.092032,0.066246,0.024917,0.056280
4498,0.044959,0.078689,0.062332,0.044707,0.073127,0.035953,0.122986,0.042383,0.067507,0.056998,0.083299,0.034141,0.072865,0.078524,0.099365
4499,0.062013,0.075756,0.057622,0.084593,0.042129,0.036083,0.023906,0.036930,0.046888,0.111745,0.105454,0.044794,0.087330,0.112658,0.064113

In [ ]:
dict1=dict()
dict1=dict(zip(range(0,15),y_obs.columns))
dict1

{0: 'genus_Acer',
 1: 'genus_Fraxinus',
 2: 'genus_Ginkgo',
 3: 'genus_Gleditsia',
 4: 'genus_Koelreuteria',
 5: 'genus_Liquidambar',
 6: 'genus_Platanus',
 7: 'genus_Prunus',
 8: 'genus_Pyrus',
 9: 'genus_Quercus',
 10: 'genus_Styphnolobium',
 11: 'genus_Syringa',
 12: 'genus_Tilia',
 13: 'genus_Ulmus',
 14: 'genus_Zelkova'}

In [ ]:
df1.rename(columns=dict1, inplace=True)
df1

,genus_Acer,genus_Fraxinus,genus_Ginkgo,genus_Gleditsia,genus_Koelreuteria,genus_Liquidambar,genus_Platanus,genus_Prunus,genus_Pyrus,genus_Quercus,genus_Styphnolobium,genus_Syringa,genus_Tilia,genus_Ulmus,genus_Zelkova
0,0.093703,0.084574,0.068281,0.058319,0.039194,0.040789,0.041499,0.062922,0.071285,0.075300,0.081834,0.062797,0.085327,0.081089,0.049580
1,0.155485,0.119135,-0.000724,0.045550,0.059175,0.223421,0.019762,0.039941,0.161894,0.042359,0.016860,0.053506,0.019007,0.040662,0.017472
2,0.051246,0.077182,0.079923,0.041109,0.083857,0.033001,0.066534,0.094443,0.031681,0.059697,0.087946,0.100923,0.085255,0.039299,0.069240
3,0.120817,0.071793,0.064686,0.038733,0.036157,0.044469,0.045697,0.070579,0.092363,0.047515,0.068305,0.068903,0.076764,0.075945,0.040081
4,0.137708,0.061962,0.001551,0.043168,0.105068,0.230636,0.053192,0.053875,0.102783,0.046827,0.031712,0.062022,0.026671,0.041662,0.029435
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,0.048766,0.114880,0.018295,0.105246,0.064188,0.033396,0.085104,0.068094,0.045833,0.077913,0.071677,0.045953,0.084643,0.049009,0.078136
4496,0.064362,0.071293,0.024489,0.012413,-0.003322,0.225118,0.015266,0.074844,0.243836,0.025929,0.009187,0.049409,0.041082,0.014237,0.025991
4497,0.057087,0.115284,0.076345,0.070999,0.058297,0.010932,0.089748,0.071200,0.041404,0.095307,0.061041,0.092032,0.066246,0.024917,0.056280
4498,0.044959,0.078689,0.062332,0.044707,0.073127,0.035953,0.122986,0.042383,0.067507,0.056998,0.083299,0.034141,0.072865,0.078524,0.099365
4499,0.062013,0.075756,0.057622,0.084593,0.042129,0.036083,0.023906,0.036930,0.046888,0.111745,0.105454,0.044794,0.087330,0.112658,0.064113

In [ ]:
df1.idxmax(1)

0              genus_Acer
1       genus_Liquidambar
2           genus_Syringa
3              genus_Acer
4       genus_Liquidambar
              ...
4495       genus_Fraxinus
4496          genus_Pyrus
4497       genus_Fraxinus
4498       genus_Platanus
4499          genus_Ulmus
Length: 4500, dtype: object

In [ ]:
result['Max']= df1.idxmax(axis=1)

In [ ]:
result['Max'] = result['Max'].str.split('_').apply(lambda x: x[1])
result

       latitude  longitude    genus          Max
0     40.871645 -73.852622     Acer         Acer
1     40.561168 -74.181661     Acer  Liquidambar
2     40.684241 -73.788480     Acer      Syringa
3     40.863976 -73.830723     Acer         Acer
4     40.588873 -74.153231     Acer  Liquidambar
...         ...        ...      ...          ...
4495  40.709965 -73.897958  Zelkova     Fraxinus
4496  40.510212 -74.234147  Zelkova        Pyrus
4497  40.697813 -73.841222  Zelkova     Fraxinus
4498  40.614405 -73.985595  Zelkova     Platanus
4499  40.877681 -73.885259  Zelkova        Ulmus

[4500 rows x 4 columns]

In [ ]:
len(result.loc[result['Max']==result['genus']])

705

In [ ]:
len(result.loc[result['Max']=='Acer'])

1403

In [ ]:
result.Max.unique()

array(['Acer', 'Liquidambar', 'Syringa', 'Quercus', 'Pyrus', 'Fraxinus',
       'Gleditsia', 'Ginkgo', 'Platanus', 'Prunus', 'Ulmus', 'Zelkova',
       'Tilia', 'Styphnolobium', 'Koelreuteria'], dtype=object)

In [ ]:
df_new1=pd.get_dummies(df_new1)
df_new1['health']=df_new['health']
dict1= {'Poor':0, 'Fair':0.5,'Good':1}
df_new1['health'].replace(dict1, inplace=True)
df_new1

,latitude,longitude,genus_Acer,genus_Cercis,genus_Fraxinus,genus_Ginkgo,genus_Gleditsia,genus_Liquidambar,genus_Platanus,genus_Prunus,genus_Pyrus,genus_Quercus,genus_Styphnolobium,genus_Syringa,genus_Tilia,genus_Ulmus,genus_Zelkova,health
0,40.723092,-73.844215,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.5
1,40.794111,-73.818679,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0.5
2,40.713537,-73.934456,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1.0
3,40.666778,-73.975979,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1.0
4,40.762724,-73.987297,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440050,40.645694,-73.958179,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1.0
440051,40.713211,-73.954944,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1.0
440052,40.620762,-74.136517,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0
440053,40.850828,-73.903115,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0
440054,40.732165,-73.787526,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.5

In [ ]:
!pip install pgmpy

Collecting pgmpy
  Using cached pgmpy-0.1.18-py3-none-any.whl (1.9 MB)
Requirement already satisfied: pyparsing in c:\anaconda3\envs\geo\lib\site-packages (from pgmpy) (2.4.7)
Requirement already satisfied: scikit-learn in c:\anaconda3\envs\geo\lib\site-packages (from pgmpy) (1.0)
Requirement already satisfied: tqdm in c:\anaconda3\envs\geo\lib\site-packages (from pgmpy) (4.62.3)
Requirement already satisfied: networkx in c:\anaconda3\envs\geo\lib\site-packages (from pgmpy) (2.5)
Requirement already satisfied: pandas in c:\anaconda3\envs\geo\lib\site-packages (from pgmpy) (1.3.4)
Collecting torch
  Downloading torch-1.11.0-cp37-cp37m-win_amd64.whl (158.0 MB)
Requirement already satisfied: joblib in c:\anaconda3\envs\geo\lib\site-packages (from pgmpy) (1.1.0)
Requirement already satisfied: numpy in c:\anaconda3\envs\geo\lib\site-packages (from pgmpy) (1.21.3)
Requirement already satisfied: statsmodels in c:\anaconda3\envs\geo\lib\site-packages (from pgmpy) (0.13.0)
Requirement already satisfied: scipy in c:\anaconda3\envs\geo\lib\site-packages (from pgmpy) (1.7.1)
Requirement already satisfied: decorator>=4.3.0 in c:\anaconda3\envs\geo\lib\site-packages (from networkx->pgmpy) (5.1.0)
Requirement already satisfied: pytz>=2017.3 in c:\anaconda3\envs\geo\lib\site-packages (from pandas->pgmpy) (2021.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\anaconda3\envs\geo\lib\site-packages (from pandas->pgmpy) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\anaconda3\envs\geo\lib\site-packages (from python-dateutil>=2.7.3->pandas->pgmpy) (1.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\anaconda3\envs\geo\lib\site-packages (from scikit-learn->pgmpy) (3.0.0)
Requirement already satisfied: patsy>=0.5.2 in c:\anaconda3\envs\geo\lib\site-packages (from statsmodels->pgmpy) (0.5.2)
Requirement already satisfied: typing-extensions in c:\anaconda3\envs\geo\lib\site-packages (from torch->pgmpy) (3.10.0.2)
Requirement already satisfied: colorama in c:\anaconda3\envs\geo\lib\site-packages (from tqdm->pgmpy) (0.4.4)
Installing collected packages: torch, pgmpy
Successfully installed pgmpy-0.1.18 torch-1.11.0

In [ ]:
import pandas as pd
import numpy as np
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, WhiteKernel
from matplotlib import pyplot as plt
from pgmpy.estimators import HillClimbSearch, BicScore
import matplotlib.pylab as plt

In [ ]:
df_new1.columns

Index(['latitude', 'longitude', 'genus_Acer', 'genus_Cercis', 'genus_Fraxinus',
       'genus_Ginkgo', 'genus_Gleditsia', 'genus_Liquidambar',
       'genus_Platanus', 'genus_Prunus', 'genus_Pyrus', 'genus_Quercus',
       'genus_Styphnolobium', 'genus_Syringa', 'genus_Tilia', 'genus_Ulmus',
       'genus_Zelkova', 'health'],
      dtype='object')

In [ ]:
X_obs = df_new1[['latitude', 'longitude', 'genus_Acer', 'genus_Cercis', 'genus_Fraxinus',
       'genus_Ginkgo', 'genus_Gleditsia', 'genus_Liquidambar',
       'genus_Platanus', 'genus_Prunus', 'genus_Pyrus', 'genus_Quercus',
       'genus_Styphnolobium', 'genus_Syringa', 'genus_Tilia', 'genus_Ulmus',
       'genus_Zelkova']]
y_obs = df_new1[ 'health']

In [ ]:
kernel = 1.* RBF(length_scale=1., length_scale_bounds=(1e-3, 1e3)) \
    + WhiteKernel(noise_level=1., noise_level_bounds=(1e-10, 1e10))

gp = GaussianProcessRegressor(kernel=kernel,random_state=1)

gp.fit(X_obs, y_obs)

y_mesh_pred, sigma = gp.predict(X_obs, return_std=True)

print(gp.kernel_)